// src/main/resources/application.properties
spring.application.name=biblioteca

# mongodb+srv://USUARIO:SENHA@cluster0.p737yt3.mongodb.net/NOMEDB?appName=Cluster0
spring.data.mongodb.uri=mongodb+srv://nicholas_db:200604@cluster0.p737yt3.mongodb.net/biblioteca?appName=Cluster0
spring.thymeleaf.cache=false
server.port=8080